import { Github, Linkedin, Mail, Twitter } from "lucide-react";

export const DATA = {
  name: "Cristhian Ferreira",
  initials: "CF",
  location: "Santo Domingo, Dominican Republic",
  locationLink: "https://www.google.com/maps/place/Santo+Domingo",
  description:
    "Backend Engineer. I build scalable, secure APIs and AI-powered systems for real-world applications.",
  summary:
    "Backend Engineer with 5+ years of experience building high-performance systems in healthcare, e‑commerce, and education. Specialized in Python, FastAPI, Django, AWS, and Generative AI. Strong engineering discipline using TDD, clean architecture, CI/CD, and cloud‑native tooling.",
  avatarUrl: "/profile.png",
  skills: [
    "Python",
    "FastAPI",
    "Django",
    "Flask",
    "LangChain",
    "AWS",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "Docker",
    "GitHub Actions",
    "CI/CD",
    "NLP",
    "Speech Recognition",
    "JavaScript",
    "React",
  ],
  contact: {
    email: "cferreirasuazo@gmail.com",
    tel: "+18297211232",
    social: {
      GitHub: {
        name: "GitHub",
        url: "https://github.com/cferreiradev",
        icon: Github,
      },
      LinkedIn: {
        name: "LinkedIn",
        url: "https://www.linkedin.com/in/cferreira-7159b8110/",
        icon: Linkedin,
      },
      Email: {
        name: "Send Email",
        url: "mailto:cferreirasuazo@gmail.com",
        icon: Mail,
      },
    },
  },
  work: [
    {
      company: "Neural Technology Solutions",
      href: "#",
      badges: [],
      location: "Santo Domingo, Dominican Republic",
      title: "Senior API Developer (Python)",
      logoUrl: "/neuraltech.png",
      start: "2025",
      end: "Present",
      description:
        "Developed a clinical trials form‑building platform using Python, Flask, and Connexion with OpenAPI 3.0. Automated CI/CD pipelines and ensured compliance with medical data standards while collaborating with cross‑functional teams.",
    },
    {
      company: "Crecerlab",
      href: "#",
      badges: [],
      location: "Santo Domingo, Dominican Republic",
      title: "AI Applied Engineer",
      logoUrl: "/crecerlab.png",
      start: "2024",
      end: "2025",
      description:
        "Built scalable FastAPI services integrating LLMs (ChatGPT, Claude) and LangChain. Implemented WhatsApp Business API integrations, Cardnet payment gateway, and optimized backend performance using TDD and clean architecture.",
    },
    {
      company: "Codemera S.R.L",
      href: "#",
      badges: [],
      location: "Santo Domingo, Dominican Republic",
      title: "Fullstack Developer",
      logoUrl: "/codemera.png",
      start: "2020",
      end: "2024",
      description:
        "Rebuilt Kastaco’s backend with Django Rest Framework. Enhanced Printhouse’s e‑commerce platform, integrating external systems and improving conversions. Worked with Python, Rails, PostgreSQL, and cloud deployment tools.",
    },
    {
      company: "Malla Agency",
      href: "#",
      badges: [],
      location: "Dominican Republic",
      title: "Software Developer — Consultant",
      logoUrl: "/malla.png",
      start: "2023",
      end: "2024",
      description:
        "Developed custom software solutions and provided technical support. Improved system workflows through algorithmic optimizations using Python, JavaScript, and SQL.",
    },
    {
      company: "OZ Sports",
      href: "#",
      badges: [],
      location: "Santo Domingo, Dominican Republic",
      title: "Linux Administration & Technical Support",
      logoUrl: "/ozsports.png",
      start: "2019",
      end: "2020",
      description:
        "Managed Linux servers for OTT services ensuring 99.9% uptime. Automated administrative tasks with shell scripting, improving operational efficiency by 20%.",
    },
  ],
  education: [
    {
      school: "ExamPro — GenAI Bootcamp",
      href: "#",
      degree: "AI Engineer",
      logoUrl: "/exampro.png",
      start: "2025",
      end: "2025",
    },
    {
      school: "Coursera",
      href: "#",
      degree: "Software Design & Architecture Specialization",
      logoUrl: "/coursera.png",
      start: "2022",
      end: "2022",
    },
    {
      school: "Universidad Dominicana O&M",
      href: "#",
      degree: "B.S. Systems Engineering",
      logoUrl: "/udom.png",
      start: "2017",
      end: "2021",
    },
  ],
  projects: [
    {
      title: "Japanese Text Adventure Game",
      href: "#",
      dates: "2025",
      active: true,
      description:
        "An AI‑powered language learning game using NLP to dynamically introduce vocabulary as the story evolves.",
      technologies: ["FastAPI", "LLMs", "LangChain", "Python"],
      links: [],
      image: "/jp-game.png",
      video: "",
    },
    {
      title: "Speech‑to‑Learn App",
      href: "#",
      dates: "2025",
      active: true,
      description:
        "Real‑time speech recognition learning platform evaluating ASR models and providing instant feedback.",
      technologies: ["ASR", "Python", "FastAPI", "Deep Learning"],
      links: [],
      image: "/speech-app.png",
      video: "",
    },
    {
      title: "ASL Finger‑Spelling Recognition",
      href: "#",
      dates: "2025",
      active: true,
      description:
        "Computer‑vision model for recognizing ASL finger‑spelling gestures for educational use.",
      technologies: ["Computer Vision", "Python", "Deep Learning"],
      links: [],
      image: "/asl-app.png",
      video: "",
    },
  ],
};
